config/routes.rb
Carsweb::Application.routes.draw do

  resources :cars
  
  resources :users
  get 'brandnew/cars/show_models'
  %w{cars car_models owners}.each do |class_name|
 scope :module => "backend" do
  resources class_name.to_sym , :path=>"/backend/#{class_name}" , :as => "backend_#{class_name}".to_sym
 end
end
scope :module => "brandnew" do
  resources :cars , :path=>"/brandnew/cars" , :as => :brandnew_cars
 end
scope :module => "backend/brandnew" do
  resources :cars , :path=>"/backend/brandnew/cars" , :as => :backend_brandnew_cars
 end

   root :to => 'cars#index'
   
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'admin_signout', :to=> "cars#destroy_admin"
  match 'mycars', :to => "cars#mycars"

end

app/models/car.rb
class Car < ActiveRecord::Base
belongs_to :car_model
#belongs_to :owner
belongs_to :user

def self.search(price_from,price_to,used)
   if (price_from && price_to&&used)
    find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =?",used])
   else
   find(:all)
   end
 end

def self.search1(price_from,price_to,used,id)
  find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=?",used,id])
end

end

app/controllers/backend/brandnew/cars_controller.rb
class Backend::Brandnew::CarsController < ApplicationController
  # GET /backend/brandnew/cars
  # GET /backend/brandnew/cars.json
  def index
    @backend_brandnew_cars =Car.where(:used=>false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backend_brandnew_cars }
    end
  end

  # GET /backend/brandnew/cars/1
  # GET /backend/brandnew/cars/1.json
  def show
    @backend_brandnew_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @backend_brandnew_car }
    end
  end

  # GET /backend/brandnew/cars/new
  # GET /backend/brandnew/cars/new.json
  def new
    @backend_brandnew_car = Car.new
    @models=CarModel.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @backend_brandnew_car }
    end
  end

  # GET /backend/brandnew/cars/1/edit
  def edit
    @backend_brandnew_car = Car.find(params[:id])
    @models=CarModel.all
  end

  # POST /backend/brandnew/cars
  # POST /backend/brandnew/cars.json
  def create
    @backend_brandnew_car =Car.new(params[:backend_brandnew_car])
    @models=CarModel.all

    respond_to do |format|
      @backend_brandnew_car.used=false
      if @backend_brandnew_car.save
        format.html { redirect_to backend_brandnew_car_path(@backend_brandnew_car), notice: 'Car was successfully created.' }
        format.json { render json: @backend_brandnew_car, status: :created, location: @backend_brandnew_car }
      else
        format.html { render action: "new" }
        format.json { render json: @backend_brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backend/brandnew/cars/1
  # PUT /backend/brandnew/cars/1.json
  def update
    @backend_brandnew_car = Car.find(params[:id])

    respond_to do |format|
      if @backend_brandnew_car.update_attributes(params[:backend_brandnew_car])
        format.html { redirect_to backend_brandnew_car_path(@backend_brandnew_car), notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @backend_brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/brandnew/cars/1
  # DELETE /backend/brandnew/cars/1.json
  def destroy
    @backend_brandnew_car = Car.find(params[:id])
    @backend_brandnew_car.destroy

    respond_to do |format|
      format.html { redirect_to backend_brandnew_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/backend/cars_controller.rb
class Backend::CarsController < ApplicationController
  # GET /backend/cars
  # GET /backend/cars.json
  def index
    @backend_cars = Car.where(:used=>true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backend_cars }
    end
  end

  # GET /backend/cars/1
  # GET /backend/cars/1.json
  def show
    @backend_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @backend_car }
    end
  end

  # GET /backend/cars/new
  # GET /backend/cars/new.json
  def new
    #logger.debug(">>>>>backend new")
    @backend_car = Car.new
    @models=CarModel.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @backend_car }
    end
  end

  # GET /backend/cars/1/edit
  def edit
    @models=CarModel.all
    @backend_car = Car.find(params[:id])
  end

  # POST /backend/cars
  # POST /backend/cars.json
  def create
    @backend_car = Car.new(params[:backend_car])
    #logger.debug(">>>>>create")

    respond_to do |format|
      @backend_car.used=true
      if @backend_car.save
        format.html { redirect_to backend_car_path(@backend_car), notice: 'Car was successfully created.' }
        logger.debug(">>>>>backend format html create")
        format.json { render json: @backend_car, status: :created, location: backend_car_path(@backend_car) }
      else
        format.html { render action: "new" }
        format.json { render json: @backend_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backend/cars/1
  # PUT /backend/cars/1.json
  def update
    @backend_car = Car.find(params[:id])

    respond_to do |format|
      if @backend_car.update_attributes(params[:backend_car])
        format.html { redirect_to backend_car_path(@backend_car), notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @backend_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/cars/1
  # DELETE /backend/cars/1.json
  def destroy
    @backend_car = Car.find(params[:id])
    @backend_car.destroy

    respond_to do |format|
      format.html { redirect_to backend_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/brandnew/cars_controller.rb
class Brandnew::CarsController < ApplicationController

  def show_models
  @car_models=CarModel.all
  end

  # GET /brandnew/cars
  # GET /brandnew/cars.json
  def index

  @params=params
  @car_id=params[:car_name] || session[:car_name]
  @car_door=params[:doors] || flash[:doors]
  price_from=params[:PriceFrom] || flash[:PriceFrom]
  price_to=params[:PriceTo] || flash[:PriceTo]
  if params[:car_name]!=session[:car_name] or params[:PriceFrom] != flash[:PriceFrom] or params[:PriceTo] != flash[:PriceTo] or params[:doors]!=flash[:doors]


  session[:car_name]=@car_id
  flash[:PriceFrom]=price_from
  flash[:PriceTo]=price_to
  flash[:doors]=@car_door
 # flash[:PriceTo]=@car_door  , :doors=>@car_door


  redirect_to :car_name => @car_id ,:PriceFrom => price_from , :PriceTo => price_to ,:doors=>@car_door and return

  end
    
    
if(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo] && params[:doors]!="" && params[:doors])
     @brandnew_cars=Car.find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=? AND doors=?",false,@car_id,@car_door])
  
    elsif (params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @brandnew_cars=Car.find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=?",false,@car_id])
    elsif(params[:PriceFrom] =="" && params[:PriceTo] ==""&& params[:doors] && params[:doors]!="")
      @brandnew_cars=Car.where(:used=>false,:car_model_id=>@car_id,:doors=>@car_door).order(params[:sort])

     else(params[:PriceFrom] =="" && params[:PriceTo] =="")
      @brandnew_cars=Car.where(:used=>false,:car_model_id=>@car_id).order(params[:sort])
   
   
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brandnew_cars }
    end
  end

  # GET /brandnew/cars/1
  # GET /brandnew/cars/1.json
  def show
    @brandnew_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brandnew_car }
    end
  end

  # GET /brandnew/cars/new
  # GET /brandnew/cars/new.json
  def new
    @brandnew_car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brandnew_car }
    end
  end

  # GET /brandnew/cars/1/edit
  def edit
    @brandnew_car = Car.find(params[:id])
  end

  # POST /brandnew/cars
  # POST /brandnew/cars.json
  def create
    @brandnew_car = Car.new(params[:brandnew_car])

    respond_to do |format|
      if @brandnew_car.save
        format.html { redirect_to @brandnew_car, notice: 'Car was successfully created.' }
        format.json { render json: @brandnew_car, status: :created, location: @brandnew_car }
      else
        format.html { render action: "new" }
        format.json { render json: @brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brandnew/cars/1
  # PUT /brandnew/cars/1.json
  def update
    @brandnew_car = Car.find(params[:id])

    respond_to do |format|
      if @brandnew_car.update_attributes(params[:brandnew_car])
        format.html { redirect_to @brandnew_car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brandnew/cars/1
  # DELETE /brandnew/cars/1.json
  def destroy
    @brandnew_car = Car.find(params[:id])
    @brandnew_car.destroy

    respond_to do |format|
      format.html { redirect_to brandnew_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
   if (params[:id] != "" && params[:id]&&params[:doors] && params[:doors]!= ""&&params[:PriceFrom]&&params[:PriceFrom]!= ""&& params[:PriceFrom]&&params[:PriceTo]!= "")
      @cars=Car.search_price_door_carid(params[:PriceFrom],params[:PriceTo],true,params[:doors],params[:id])
      @car_doors=params[:doors]
      @model_id=params[:id]

     elsif (params[:doors] && params[:doors]!= ""&&params[:PriceFrom]&&params[:PriceFrom]!= ""&& params[:PriceFrom]&&params[:PriceTo]!= "")
      @car_doors=params[:doors]
      @cars=Car.search_price_door(params[:PriceFrom],params[:PriceTo],true,params[:doors])

    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo] && params[:id] != "" && params[:id])
      @cars=Car.search_price_carid(params[:PriceFrom],params[:PriceTo],true,params[:id])
      @model_id=params[:id]

    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @cars=Car.search(params[:PriceFrom],params[:PriceTo],true)

    elsif (params[:doors])
      @car_doors=params[:doors]
      @cars=Car.where(:doors=>@car_doors,:used=>true)

    elsif (params[:id] != "" && params[:id])
      @model_id=params[:id]
      @cars = Car.order(params[:sort]).where(:car_model_id=>params[:id],:used=>true)

    else
    @cars=Car.order(params[:sort]).where(:used=>true)

    end
    @models=CarModel.all
    
    #logger.debug params[:user]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new
    @models= CarModel.get_models_names
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
    @models= CarModel.get_models_names
  end
  
  def mycars
    if session[:user_id]
      user = User.find(session[:user_id])
      #@cars = user.cars 
    if(params[:id] != "" && params[:id])
      @model_id=params[:id]
      @cars = user.cars.order(params[:sort]).where(:car_model_id=>params[:id])
    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @cars=user.cars.search(params[:PriceFrom],params[:PriceTo])
    else
    @cars=user.cars.order(params[:sort]).all
    end
    @models=CarModel.all
    end
  end
  # POST /cars
  # POST /cars.json
  def create
    if params[:user]
      if params[:user][:name]=='admin' && params[:user][:password]=='admin'
        session[:admin]=true
        flash[:notice] = "successfully logged in as administrator"
        redirect_to cars_path
      else
        flash[:notice] = "Wrong administrator username and password"
        redirect_to cars_path
      end
      
    else
       @car = Car.new(params[:car])
      #logger.debug(@car.inspect)
      respond_to do |format|
        if @car.save
          format.html { redirect_to @car, notice: 'Car was successfully created.' }
          format.json { render json: @car, status: :created, location: @car }
        else
          format.html { render action: "new" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end 
    end
    
  end
  
  def destroy_admin
    session[:admin]=nil
    redirect_to cars_path
  end
  
  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/backend/brandnew/cars_helper.rb
module Backend::Brandnew::CarsHelper
end

app/helpers/backend/cars_helper.rb
module Backend::CarsHelper
end

app/helpers/brandnew/cars_helper.rb
module Brandnew::CarsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/backend/brandnew/cars/_form.html.erb
<%= form_for(@backend_brandnew_car, :url => url_for(:controller => 'backend/brandnew/cars', :action => 'new'),:method=>"get") do |f| %>
  

  <% if @backend_brandnew_car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backend_brandnew_car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @backend_brandnew_car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label :car_model_id, t("activerecord.attributes.car.car_model_id", :default => "Car model"), :class => :label %>
    <%= f.select :car_model_id, options_from_collection_for_select(@models, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :cylinders %><br />
    <%= f.number_field :cylinders %>
  </div>
  <div class="field">
    <%= f.label :horse_power %><br />
    <%= f.number_field :horse_power %>
  </div>
  <div class="field">
    <%= f.label :doors %><br />
    <%= f.number_field :doors %>
  </div>
  <div class="field">
    <%= f.label :air_bags %><br />
    <%= f.check_box :air_bags %>
  </div>
  <div class="field">
    <%= f.label :abs %><br />
    <%= f.check_box :abs %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backend/brandnew/cars/edit.html.erb
<h1>Editing backend_brandnew_car</h1>

<%= render 'form' ,:locals => {:path=>backend_brandnew_car_path}%>

<%= link_to 'Show', backend_brandnew_car_path(@backend_brandnew_car) %> |
<%= link_to 'Back', backend_brandnew_cars_path %>

app/views/backend/brandnew/cars/index.html.erb
<div class="secondary-navigation">
    <ul class="wat-cf">
      <li><%= link_to "#{t("web-app-theme.list", :default => "Cars")}", backend_cars_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "Cars Model")}", backend_car_models_path %></li>
      <li class="first active"><%= link_to "#{t("web-app-theme.new", :default => "New Car")}", backend_brandnew_cars_path %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "User View")}", cars_path %></li>
    </ul>
  </div>
<h1>New cars</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Model</th>
    <th>Cylinders</th>
    <th>Horse power</th>
    <th>Doors</th>
    <th>Air bags</th>
    <th>Abs</th>
    <th>Price</th>
  </tr>

<% @backend_brandnew_cars.each do |backend_brandnew_car| %>
  <tr>
    <td><%= backend_brandnew_car.year %></td>
    <td><%= backend_brandnew_car.car_model.name %></td>
    <td><%= backend_brandnew_car.cylinders %></td>
    <td><%= backend_brandnew_car.horse_power %></td>
    <td><%= backend_brandnew_car.doors %></td>
    <td><%= backend_brandnew_car.air_bags %></td>
    <td><%= backend_brandnew_car.abs %></td>
    <td><%= backend_brandnew_car.price %></td>

    <td><%= link_to 'Show', backend_brandnew_car_path(backend_brandnew_car) %></td>
    <td><%= link_to 'Edit', edit_backend_brandnew_car_path(backend_brandnew_car) %></td>
    <td><%= link_to 'Destroy', backend_brandnew_car_path(backend_brandnew_car), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_backend_brandnew_car_path %>

app/views/backend/brandnew/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' ,:locals => {:path=>backend_brandnew_cars_path}%>

<%= link_to 'Back', backend_brandnew_cars_path %>

app/views/backend/brandnew/cars/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Model:</b>
  <%= @backend_brandnew_car.car_model.name %>
</p>
<p>
  <b>Year:</b>
  <%= @backend_brandnew_car.year %>
</p>

<p>
  <b>Cylinders:</b>
  <%= @backend_brandnew_car.cylinders %>
</p>

<p>
  <b>Horse power:</b>
  <%= @backend_brandnew_car.horse_power %>
</p>

<p>
  <b>Doors:</b>
  <%= @backend_brandnew_car.doors %>
</p>

<p>
  <b>Air bags:</b>
  <%= @backend_brandnew_car.air_bags %>
</p>

<p>
  <b>Abs:</b>
  <%= @backend_brandnew_car.abs %>
</p>

<p>
  <b>Price:</b>
  <%= @backend_brandnew_car.price %>
</p>



<%= link_to 'Edit', edit_backend_brandnew_car_path(@backend_brandnew_car) %> |
<%= link_to 'Back', backend_brandnew_cars_path %>