config/routes.rb
Carsweb::Application.routes.draw do

  resources :cars
  
  resources :users
  get 'brandnew/cars/show_models'
  %w{cars car_models owners}.each do |class_name|
 scope :module => "backend" do
  resources class_name.to_sym , :path=>"/backend/#{class_name}" , :as => "backend_#{class_name}".to_sym
 end
end
scope :module => "brandnew" do
  resources :cars , :path=>"/brandnew/cars" , :as => :brandnew_cars
 end
scope :module => "backend/brandnew" do
  resources :cars , :path=>"/backend/brandnew/cars" , :as => :backend_brandnew_cars
 end

   root :to => 'cars#index'
   
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'admin_signout', :to=> "cars#destroy_admin"
  match 'mycars', :to => "cars#mycars"

end

app/models/car.rb
class Car < ActiveRecord::Base
belongs_to :car_model
#belongs_to :owner
belongs_to :user

def self.search(price_from,price_to,used)
   if (price_from && price_to&&used)
    find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =?",used])
   else
   find(:all)
   end
 end

def self.search1(price_from,price_to,used,id)
  find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=?",used,id])
end

end

app/controllers/backend/brandnew/cars_controller.rb
class Backend::Brandnew::CarsController < ApplicationController
  # GET /backend/brandnew/cars
  # GET /backend/brandnew/cars.json
  def index
    @backend_brandnew_cars =Car.where(:used=>false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backend_brandnew_cars }
    end
  end

  # GET /backend/brandnew/cars/1
  # GET /backend/brandnew/cars/1.json
  def show
    @backend_brandnew_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @backend_brandnew_car }
    end
  end

  # GET /backend/brandnew/cars/new
  # GET /backend/brandnew/cars/new.json
  def new
    @backend_brandnew_car = Car.new
    @models=CarModel.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @backend_brandnew_car }
    end
  end

  # GET /backend/brandnew/cars/1/edit
  def edit
    @backend_brandnew_car = Car.find(params[:id])
    @models=CarModel.all
  end

  # POST /backend/brandnew/cars
  # POST /backend/brandnew/cars.json
  def create
    @backend_brandnew_car =Car.new(params[:backend_brandnew_car])
    @models=CarModel.all

    respond_to do |format|
      @backend_brandnew_car.used=false
      if @backend_brandnew_car.save
        format.html { redirect_to backend_brandnew_car_path(@backend_brandnew_car), notice: 'Car was successfully created.' }
        format.json { render json: @backend_brandnew_car, status: :created, location: @backend_brandnew_car }
      else
        format.html { render action: "new" }
        format.json { render json: @backend_brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backend/brandnew/cars/1
  # PUT /backend/brandnew/cars/1.json
  def update
    @backend_brandnew_car = Car.find(params[:id])

    respond_to do |format|
      if @backend_brandnew_car.update_attributes(params[:backend_brandnew_car])
        format.html { redirect_to backend_brandnew_car_path(@backend_brandnew_car), notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @backend_brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/brandnew/cars/1
  # DELETE /backend/brandnew/cars/1.json
  def destroy
    @backend_brandnew_car = Car.find(params[:id])
    @backend_brandnew_car.destroy

    respond_to do |format|
      format.html { redirect_to backend_brandnew_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/backend/cars_controller.rb
class Backend::CarsController < ApplicationController
  # GET /backend/cars
  # GET /backend/cars.json
  def index
    @backend_cars = Car.where(:used=>true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backend_cars }
    end
  end

  # GET /backend/cars/1
  # GET /backend/cars/1.json
  def show
    @backend_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @backend_car }
    end
  end

  # GET /backend/cars/new
  # GET /backend/cars/new.json
  def new
    #logger.debug(">>>>>backend new")
    @backend_car = Car.new
    @models=CarModel.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @backend_car }
    end
  end

  # GET /backend/cars/1/edit
  def edit
    @models=CarModel.all
    @backend_car = Car.find(params[:id])
  end

  # POST /backend/cars
  # POST /backend/cars.json
  def create
    @backend_car = Car.new(params[:backend_car])
    #logger.debug(">>>>>create")

    respond_to do |format|
      @backend_car.used=true
      if @backend_car.save
        format.html { redirect_to backend_car_path(@backend_car), notice: 'Car was successfully created.' }
        logger.debug(">>>>>backend format html create")
        format.json { render json: @backend_car, status: :created, location: backend_car_path(@backend_car) }
      else
        format.html { render action: "new" }
        format.json { render json: @backend_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backend/cars/1
  # PUT /backend/cars/1.json
  def update
    @backend_car = Car.find(params[:id])

    respond_to do |format|
      if @backend_car.update_attributes(params[:backend_car])
        format.html { redirect_to backend_car_path(@backend_car), notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @backend_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/cars/1
  # DELETE /backend/cars/1.json
  def destroy
    @backend_car = Car.find(params[:id])
    @backend_car.destroy

    respond_to do |format|
      format.html { redirect_to backend_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/brandnew/cars_controller.rb
class Brandnew::CarsController < ApplicationController

  def show_models
  @car_models=CarModel.all
  end

  # GET /brandnew/cars
  # GET /brandnew/cars.json
  def index

  @params=params
  @car_id=params[:car_name] || session[:car_name]
  @car_door=params[:doors] || flash[:doors]
  price_from=params[:PriceFrom] || flash[:PriceFrom]
  price_to=params[:PriceTo] || flash[:PriceTo]
  if params[:car_name]!=session[:car_name] or params[:PriceFrom] != flash[:PriceFrom] or params[:PriceTo] != flash[:PriceTo] or params[:doors]!=flash[:doors]


  session[:car_name]=@car_id
  flash[:PriceFrom]=price_from
  flash[:PriceTo]=price_to
  flash[:doors]=@car_door
 # flash[:PriceTo]=@car_door  , :doors=>@car_door


  redirect_to :car_name => @car_id ,:PriceFrom => price_from , :PriceTo => price_to ,:doors=>@car_door and return

  end
    
    
if(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo] && params[:doors]!="" && params[:doors])
     @brandnew_cars=Car.find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=? AND doors=?",false,@car_id,@car_door])
  
    elsif (params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @brandnew_cars=Car.find(:all,:conditions =>["price BETWEEN #{price_from} AND #{price_to} AND used =? AND car_model_id=?",false,@car_id])
    elsif(params[:PriceFrom] =="" && params[:PriceTo] ==""&& params[:doors] && params[:doors]!="")
      @brandnew_cars=Car.where(:used=>false,:car_model_id=>@car_id,:doors=>@car_door).order(params[:sort])

     else(params[:PriceFrom] =="" && params[:PriceTo] =="")
      @brandnew_cars=Car.where(:used=>false,:car_model_id=>@car_id).order(params[:sort])
   
   
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brandnew_cars }
    end
  end

  # GET /brandnew/cars/1
  # GET /brandnew/cars/1.json
  def show
    @brandnew_car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brandnew_car }
    end
  end

  # GET /brandnew/cars/new
  # GET /brandnew/cars/new.json
  def new
    @brandnew_car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brandnew_car }
    end
  end

  # GET /brandnew/cars/1/edit
  def edit
    @brandnew_car = Car.find(params[:id])
  end

  # POST /brandnew/cars
  # POST /brandnew/cars.json
  def create
    @brandnew_car = Car.new(params[:brandnew_car])

    respond_to do |format|
      if @brandnew_car.save
        format.html { redirect_to @brandnew_car, notice: 'Car was successfully created.' }
        format.json { render json: @brandnew_car, status: :created, location: @brandnew_car }
      else
        format.html { render action: "new" }
        format.json { render json: @brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brandnew/cars/1
  # PUT /brandnew/cars/1.json
  def update
    @brandnew_car = Car.find(params[:id])

    respond_to do |format|
      if @brandnew_car.update_attributes(params[:brandnew_car])
        format.html { redirect_to @brandnew_car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brandnew_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brandnew/cars/1
  # DELETE /brandnew/cars/1.json
  def destroy
    @brandnew_car = Car.find(params[:id])
    @brandnew_car.destroy

    respond_to do |format|
      format.html { redirect_to brandnew_cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
   if (params[:id] != "" && params[:id]&&params[:doors] && params[:doors]!= ""&&params[:PriceFrom]&&params[:PriceFrom]!= ""&& params[:PriceFrom]&&params[:PriceTo]!= "")
      @cars=Car.search_price_door_carid(params[:PriceFrom],params[:PriceTo],true,params[:doors],params[:id])
      @car_doors=params[:doors]
      @model_id=params[:id]

     elsif (params[:doors] && params[:doors]!= ""&&params[:PriceFrom]&&params[:PriceFrom]!= ""&& params[:PriceFrom]&&params[:PriceTo]!= "")
      @car_doors=params[:doors]
      @cars=Car.search_price_door(params[:PriceFrom],params[:PriceTo],true,params[:doors])

    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo] && params[:id] != "" && params[:id])
      @cars=Car.search_price_carid(params[:PriceFrom],params[:PriceTo],true,params[:id])
      @model_id=params[:id]

    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @cars=Car.search(params[:PriceFrom],params[:PriceTo],true)

    elsif (params[:doors])
      @car_doors=params[:doors]
      @cars=Car.where(:doors=>@car_doors,:used=>true)

    elsif (params[:id] != "" && params[:id])
      @model_id=params[:id]
      @cars = Car.order(params[:sort]).where(:car_model_id=>params[:id],:used=>true)

    else
    @cars=Car.order(params[:sort]).where(:used=>true)

    end
    @models=CarModel.all
    
    #logger.debug params[:user]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new
    @models= CarModel.get_models_names
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
    @models= CarModel.get_models_names
  end
  
  def mycars
    if session[:user_id]
      user = User.find(session[:user_id])
      #@cars = user.cars 
    if(params[:id] != "" && params[:id])
      @model_id=params[:id]
      @cars = user.cars.order(params[:sort]).where(:car_model_id=>params[:id])
    elsif(params[:PriceFrom] !="" && params[:PriceFrom] && params[:PriceTo] !="" && params[:PriceTo])
      @cars=user.cars.search(params[:PriceFrom],params[:PriceTo])
    else
    @cars=user.cars.order(params[:sort]).all
    end
    @models=CarModel.all
    end
  end
  # POST /cars
  # POST /cars.json
  def create
    if params[:user]
      if params[:user][:name]=='admin' && params[:user][:password]=='admin'
        session[:admin]=true
        flash[:notice] = "successfully logged in as administrator"
        redirect_to cars_path
      else
        flash[:notice] = "Wrong administrator username and password"
        redirect_to cars_path
      end
      
    else
       @car = Car.new(params[:car])
      #logger.debug(@car.inspect)
      respond_to do |format|
        if @car.save
          format.html { redirect_to @car, notice: 'Car was successfully created.' }
          format.json { render json: @car, status: :created, location: @car }
        else
          format.html { render action: "new" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end 
    end
    
  end
  
  def destroy_admin
    session[:admin]=nil
    redirect_to cars_path
  end
  
  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/backend/brandnew/cars_helper.rb
module Backend::Brandnew::CarsHelper
end

app/helpers/backend/cars_helper.rb
module Backend::CarsHelper
end

app/helpers/brandnew/cars_helper.rb
module Brandnew::CarsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_header.html.erb
  	<div class="secondary-navigation">
  				    <ul class="wat-cf">
			      <li class= "<%='first active' unless ( locals[:cname]!='index')%>"><%= link_to "#{t("web-app-theme.list", :default => "Cars list")}", cars_path  %></li>
			      <li class="<%='first active' unless (!locals.nil? && locals[:cname]!='new_cars')%>"><%= link_to "#{t("web-app-theme.list", :default => "New")}", brandnew_cars_show_models_path  %></li>
			      <% if session[:user_id]%>
			      <li class="<%='first active' unless (!locals.nil? && locals[:cname]!='new')%>"><%= link_to "#{t("web-app-theme.new", :default => "Add used car")}", new_car_path %></li>
			      <li class="<%='first active' unless (!locals.nil? && locals[:cname]!='mycars')%>"><%= link_to "#{t("web-app-theme.new", :default => "My cars")}", mycars_path %></li>
			      <% end %>
			      <% if session[:admin]%>
			      <li><%= link_to "#{t("web-app-theme.new", :default => "Administration")}", backend_cars_path %></li>
			      <% end %>
			      <%if locals[:cname]=="show"%>
			      <li class="<%='first active' unless (!locals.nil? && locals[:cname]!='show')%>"><%= link_to "#{t("web-app-theme.new", :default => "Show")}", car_path(@car.id) %></li>
			      <% end %>
			      <%if locals[:cname]=="edit"%>
			      <li class="<%='first active' unless (!locals.nil? && locals[:cname]!='edit')%>"><%= link_to "#{t("web-app-theme.new", :default => "Edit")}", edit_car_path(@car.id) %></li>
			      <% end %>
			      
			    </ul>
	</div>
		   

app/views/cars/_login.html.erb
<p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Login" %></p>

app/views/cars/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/cars/edit.html.erb
<div class="block">
  <%= render "header" ,:locals => {cname:'edit'} %>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Car</h2>
    <div class="inner">
      <%= form_for @car, :url => car_path(@car), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/cars/index.html.erb
<div class="block">

  <%= render "header" , :locals => { :cname => "index" }%>

  <h4><%= flash[:notice] %></h4>
  <div class="content">
  	<table width="1265px">
  		
  		<tr>
  			<td>
		    	<h2 class="title">Cars list</h2>
		    	<div class="select"> 
	  				<% if false %><h5 style="color: black">Select Model</h5><% end %>
	  				<%= form_tag("/cars",:action => 'index', :method => "get") do %>
	        		<%= select_tag :id, options_from_collection_for_select(@models, :id, :name,@model_id), :onchange => 'submit()',:prompt => "All Models",:id=>"car_model_id" %> 
	        		<% end %>
	        		
			       <%= form_tag("/cars",:action=>'index',:method=>"get") do %>
			       <p style="color: black">Price from: 
			       <%= text_field_tag :PriceFrom,params[:PriceFrom]%>
			          to:
			       <%= text_field_tag :PriceTo,params[:PriceTo]%>
			       <%= submit_tag "Search",:id =>"search_btn"%>
			       
			       </p>
			       <% end %>
			      
			      <%= form_tag("/cars",:action=>'index',:method=>"get") do %>			       
			        <%= submit_tag "All cars",:name =>nil%>			       
			       <% end %>
			       
      
  				</div>
		    </td>
		    <td align="right">
		    	<% if !current_user %>
			    	<% if session[:admin] %>
			    		<p>Signed in as <strong>Administrator</strong>
			    		<p><%= link_to "Sign out", admin_signout_path, id: "admin_sign_out" %></p> 
			    	<% else %>
			    	Sign In as administrator:
			    	<%= form_for :user, :as => :user, :html => {:method => :post} do |f| -%>
				        <%= render :partial => "login", :locals => {:f => f} %>
				      <% end -%>
				      
			    	<% end %>
		    	<% end %>
				<div id="user_nav">
					<% if !session[:admin] %>
				  		<% if current_user %>
				    		<p>Signed in as <strong><%= current_user.name %></strong> 
				    			<img alt="Search" border="0" class="dock-item" 
									src="<%= current_user.image%>" /></p>
				    		<p><%= link_to "Sign out", signout_path, id: "sign_out" %></p>
				  		<% else %>
				    		<p>
				    			<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
				    			<%= link_to image_tag('FaceBook-icon.png',:size => "16x16"),"/auth/facebook",id: "sign_in_logo"%>
				    			
				    		</p>
				  		<% end %>
			  		<% end %>
		  	</td>
	  		</tr>
	  		<tr>
  			
  			</tr>
  	</table>
  	
	</div>
      
      
    <div class="inner">
      <table class="table">
        <tr>
          
          <th>
            <%= link_to "Price", cars_path({:sort=>"price",:id=>@model_id}),:id=>"price_sort" %> 
			
          </th>
          <th>
			Model
          </th>
          <th>
            <%= link_to "Year", cars_path({:sort=>"year",:id=>@model_id}) %> 
          </th>
          <th>
          	Owner name    	
          </th>     
          <th class="last">&nbsp;</th>
        </tr>
        <% @cars.each do |car| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= car.price.to_s+" LE" unless car.price.nil?%> 
          </td>
          <td>
            <%= link_to "#{t("web-app-theme.show", :default => car.car_model.name)}", car_path(car) %> 
          </td>
         <td>
            <%= car.year %>
          </td>
          <td>
          	<%= car.user.name unless car.user.nil?%>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", car_path(car) %>
          </td>
          
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/cars/mycars.html.erb
<%= render "header", :locals => { :cname => "mycars" }%>
<div class="select"> 
            <% if false %><h5 style="color: black">Select Model</h5><% end %>
            <%= form_tag("/mycars",:action => 'mycars', :method => "get") do %>
              <%= select_tag :id, options_from_collection_for_select(@models, :id, :name,@model_id), :onchange => 'submit()',:prompt => "All Models",:id=>"car_model_id" %> 
              <% end %>
              
             <%= form_tag("/mycars",:action=>'mycars',:method=>"get") do %>
             <p style="color: black">Price from: 
             <%= text_field_tag :PriceFrom,params[:PriceFrom]%>
                to:
             <%= text_field_tag :PriceTo,params[:PriceTo]%>
             <%= submit_tag "Search",:id =>"search_btn"%>
            
             </p>
             <% end %>
              <%= form_tag("/mycars",:action=>'mycars',:method=>"get") do %>             
              <%= submit_tag "All cars",:name =>nil%>            
             <% end %>
            
            
             
      
          </div>
<div class="inner">
      <table class="table">
        <tr>
          
          <th>
            <%= link_to "Price", mycars_path({:sort=>"price",:id=>@model_id}) %> 
			
          </th>
          <th>
			Model
          </th>
          <th>
            <%= link_to "Year", mycars_path({:sort=>"year",:id=>@model_id}) %> 
          </th>
          <th>
          	Owner name    	
          </th>     
          <th class="last">&nbsp;</th>
        </tr>
        <% @cars.each do |car| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= car.price.to_s+" LE" unless car.price.nil?%> 
          </td>
          <td>
            <%= link_to "#{t("web-app-theme.show", :default => car.car_model.name)}", car_path(car) %> 
          </td>
         <td>
            <%= car.year %>
          </td>
          <td>
          	<%= car.user.name unless car.user.nil?%>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", car_path(car) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_car_path(car) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", car_path(car), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
          
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>

app/views/cars/new.html.erb
<div class="block">
  <%= render "header", :locals => { :cname => "new" } %>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Car</h2>
    <div class="inner">
      <%= form_for :car, :url => cars_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/cars/show.html.erb
<div class="block">

  <%= render "header" ,:locals => {:cname => "show"}%>

  <div class="content">
    <div class="inner">
    
      <p>
          <b><%= t("activerecord.attributes.car.price", :default => t("activerecord.labels.price", :default => "Price")) %>:</b>
          <%= @car.price %> LE
        </p>
        <b><%= t("activerecord.attributes.car.user.id", :default => t("activerecord.labels.car.user.id", :default => "Car owner")) %>:</b>
          <%= @car.user.name %>
        </p>
         <p>
          <b><%= t("activerecord.attributes.car.car_model_id", :default => t("activerecord.labels.car_model_id", :default => "Car model")) %>:</b>
          <%= @car.car_model.name %>
        </p>
        <p>
          <b><%= t("activerecord.attributes.car.year", :default => t("activerecord.labels.year", :default => "Year")) %>:</b>
          <%= @car.year %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.car.cylinders", :default => t("activerecord.labels.cylinders", :default => "Cylinders")) %>:</b>
          <%= @car.cylinders %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.car.horse_power", :default => t("activerecord.labels.horse_power", :default => "Horse power")) %>:</b>
          <%= @car.horse_power %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.car.doors", :default => t("activerecord.labels.doors", :default => "Doors")) %>:</b>
          <%= @car.doors %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.car.air_bags", :default => t("activerecord.labels.air_bags", :default => "Air bags")) %>:</b>
          <%= @car.air_bags %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.car.abs", :default => t("activerecord.labels.abs", :default => "Abs")) %>:</b>
          <%= @car.abs %>
        </p>

        
<% if false %>
        <p>
          <b><%= t("activerecord.attributes.car.owner_id", :default => t("activerecord.labels.owner_id", :default => "Owner")) %>:</b>
          <%= @car.owner_id %>
        </p>
<%end%>
	<% if session[:user_id] && session[:user_id] == @car.user_id%>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_car_path(@car), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), car_path(@car), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>